config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'keywords#index'

  devise_for :users, only: [:registrations, :sessions, :passwords]

  resources :keywords, only: %i[index create show] do
    get 'search', on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :keywords, only: %i[index create show] do
        get 'search', on: :collection
      end
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/keyword.rb
# frozen_string_literal: true

class Keyword < ApplicationRecord
  enum status: { pending: 'pending', processing: 'processing', succeeded: 'succeeded', failed: 'failed' }

  belongs_to :user, inverse_of: :keywords
  has_many :keyword_search_entries, dependent: :destroy

  validates :content, :status, presence: true
  validates :result_page_html, presence: true, if: :succeeded?
  validates :links_count,
            presence: true,
            numericality: { greater_than_or_equal_to: 0 },
            if: :succeeded?

  after_create_commit :enqueue_scrape_job

  private

  def enqueue_scrape_job
    ScrapeKeywordJob.perform_later(keyword_id: id)
  end
end

app/models/keyword_search_entry.rb
# frozen_string_literal: true

class KeywordSearchEntry < ApplicationRecord
  enum kind: { ads: 'ads', non_ads: 'non_ads' }
  enum position: { top: 'top', bottom: 'bottom', main_search: 'main_search' }

  belongs_to :keyword

  validates :kind, :position, :urls, presence: true

  scope :belongs_to_user, ->(user_id) { joins(:keyword).where(keywords: { user_id: user_id }) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :keywords, inverse_of: :user, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/application_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ApplicationController < ActionController::API
      include(Localization)
      include(Pagy::Backend)

      rescue_from(Pagy::OverflowError) do |error|
        render_error(
          status: :unprocessable_entity,
          code: :invalid_page_number,
          detail: I18n.t('pagy.errors.overflow', max_page: error.pagy.last),
          source: error.class.name
        )
      end

      rescue_from(ActiveRecord::RecordNotFound) do |error|
        render_error(
          status: :not_found,
          code: :record_not_found,
          source: error.class.name
        )
      end

      private

      def render_error(status:, code:, detail: nil, source: nil)
        error = {
          source: source,
          detail: detail,
          code: code
        }.compact_blank

        render(json: { errors: [error] }, status: status)
      end
    end
  end
end

app/controllers/api/v1/keywords_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class KeywordsController < ApplicationController
      def index
        _, keywords = pagy(KeywordsQuery.new.call)

        render(json: ::V1::KeywordSimpleSerializer.new(keywords, is_collection: true))
      end

      def show
        keyword = Keyword.find(params[:id])
        search_entries_query = KeywordSearchEntriesQuery.new(keyword_id: keyword.id)

        render(json: ::V1::KeywordSerializer.new(keyword, params: {
                                                   search_entries_query: search_entries_query
                                                 }))
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Localization
  include Pagy::Backend

  before_action :authenticate_user!
end

app/controllers/concerns/localization.rb
# frozen_string_literal: true

module Localization
  extend ActiveSupport::Concern

  included do
    around_action :switch_locale

    protected

    def switch_locale(&action)
      locale = extract_locale_from_param || I18n.default_locale

      I18n.with_locale(locale, &action)
    end

    def extract_locale_from_param
      return params[:locale] if I18n.locale_available?(params[:locale])

      nil
    end

    private

    def default_url_options
      { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
    end
  end
end

app/controllers/keywords_controller.rb
# frozen_string_literal: true

class KeywordsController < ApplicationController
  def index
    query = KeywordsQuery.new(scope: current_user.keywords)
    pagy, keywords = pagy(query.call)

    render(locals: {
             pagy: pagy,
             keyword_collection_presenter: KeywordCollectionPresenter.new(keywords: keywords)
           })
  end

  def show
    keyword = current_user.keywords.find(params[:id])

    search_entries_query = KeywordSearchEntriesQuery.new(keyword_id: keyword.id)

    render(locals: {
             keyword: keyword,
             search_entries_query: search_entries_query
           })
  end

  def create
    form = CsvUploadForm.new(user: current_user)

    if form.save(create_params[:file])
      flash[:notice] = I18n.t('activemodel.csv.upload_success')
    else
      flash[:alert] = form.errors.full_messages
    end

    redirect_to(keywords_path)
  end

  # rubocop:disable Metrics/MethodLength, Metrics/AbcSize
  def search
    result = ScrapeResultSearchQuery.new(
      pattern: search_params[:search],
      query_type: search_params[:query_type],
      scope: KeywordSearchEntry.belongs_to_user(current_user.id)
    ).call

    render(locals: {
             search_result_presenter: SearchResultPresenter.new(search_result: result),
             search_params: search_params
           })
  rescue ActiveModel::ValidationError => error
    flash[:alert] = error.model.errors.full_messages
    redirect_to(keywords_path)
  end
  # rubocop:enable Metrics/MethodLength, Metrics/AbcSize

  private

  def create_params
    params.require(:csv_upload_form).permit(:file)
  end

  def search_params
    {
      search: params.require(:search),
      query_type: params.require(:query_type).to_sym
    }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend

  def flash_alerts
    # Normalize flash[:alert] since it can be either an array of message or a single message
    # For example, devise also use flash[:alert] to display error message and pass a single message
    alert = flash[:alert]
    return alert if alert.is_a?(Array)

    [alert]
  end
end

app/views/keywords/_keywords_table.erb
<%= turbo_stream_from("keywords") %>

<div class="keywords-table border">
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Keyword</th>
        <th scope="col">Status</th>
        <th scope="col">Uploaded at</th>
        <th scope="col"></th>
      </tr>
    </thead>

    <tbody class="keywords-table__body">
      <%= render(
        partial: "keywords_table_row",
        collection: keyword_collection_presenter.keywords,
        as: :presenter
      ) %>
    </tbody>
  </table>
</div>

app/views/keywords/_keywords_table_row.erb
<tr data-keyword-id="<%= presenter.keyword.id %>" data-testid="keyword_list_item" id="<%= "keyword_#{presenter.keyword.id}" %>">
  <td><%= presenter.keyword.id %></td>
  <td><%= presenter.keyword.content %></td>
  <td data-testid="status">
    <span class="<%= presenter.status_badge %>">
      <%= presenter.status %>
    </span>
  </td>
  <td><%= presenter.upload_time %></td>
  <td>
    <% if presenter.show_detail_link? %>
      <%= link_to(I18n.t("keywords.view_detail_link"), keyword_path(presenter.keyword)) %>
    <% end %>
  </td>
</tr>

app/views/keywords/_scrape_result_search_form.erb
<%= form_tag(
  search_keywords_path,
  method: 'get',
  class: 'scrape-result-search-form',
  data: {"testid" => "scrape-result-search-form"}
) do %>
  <%= select_tag(
    :query_type,
    options_for_select([
      [I18n.t('keywords.query_type_select_placeholder'), nil],
      [I18n.t('keywords.query_types.exact'), :exact],
      [I18n.t('keywords.query_types.partial'), :partial],
      [I18n.t('keywords.query_types.pattern'), :pattern]
    ]),
    required: true,
    class: 'p-2'
  ) %>
  <%= text_field_tag(
    :search,
    '',
    required: true,
    class: 'scrape-result-search-form__input',
    placeholder: I18n.t('keywords.search_input_placeholder')
  ) %>
  <%= submit_tag(I18n.t('shared.button.search'), name: '') %>
<% end %>

app/views/keywords/_upload_form.erb
<%= form_for(:csv_upload_form,
             as: CsvUploadForm,
             url: keywords_path,
             method: :post,
             class: 'form-csv-upload py-4 d-flex justify-content-center'
            ) do |f| %>
  <%= f.label(:file, class: 'py-2 px-3') do %>
    <span class='btn btn-success' role='button'>
      <%= I18n.t('keywords.upload') %>
    </span>
  <% end %>

  <%= f.file_field(:file, class: 'form-csv-upload__file-input d-none', accept: 'text/csv') %>
<% end %>

app/views/keywords/_url_list.html.erb
<span><%= title %>:</span>
<ul>
  <% urls.each do |url| %>
    <li data-testid="keyword_details_url"><%= url %></li>
  <% end %>
</ul>

app/views/keywords/index.html.erb
<div>
  <%= render('upload_form') %>
  <% if keyword_collection_presenter.empty? %>
    <div class="d-flex justify-content-center" data-testid="no-keyword-notice">
      <%= I18n.t('keywords.no_keyword') %>
    </div>
  <% else %>
    <%= render('keywords_table', keyword_collection_presenter: keyword_collection_presenter, pagy: pagy) %>
    <div class="keywords-table__pagination">
      <%== pagy_bootstrap_nav(pagy) %>
    </div>
  <% end %>
</div>

app/views/keywords/search.html.erb
<div>
  <div class="mb-2">
    <p data-testid="search_result_search_term"><%= I18n.t('keywords.search_term', term: search_params[:search]) %></p>
    <p data-testid="search_result_query_type"><%= I18n.t('keywords.query_type', type: search_params[:query_type]) %></p>
  </div>

  <p data-testid="search_result_total_matched_urls">
    <%= I18n.t('keywords.total_matched_urls', total_urls: search_result_presenter.total_urls) %>
  </p>

  <% search_result_presenter.search_result.each do |item| %>
    <div data-keyword-id="<%= item[:keyword_id] %>">
      <span data-testid="search_result_keyword_content">
        <%= I18n.t('keywords.keyword_content', content: item[:keyword_content]) %>
        (<a href="<%= keyword_path(item[:keyword_id]) %>"><%= I18n.t('keywords.view_detail_link').downcase %></a>)
      </span>
      <ul data-testid="search_result_url_list">
        <% item[:urls].each do |item| %>
          <li><%= item %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/keywords/show.html.erb
<a href="<%= keywords_path %>">
  <%= I18n.t('shared.link.back_to_home') %>
</a>

<div class="d-flex flex-column justify-content-center mt-4">
  <p data-testid="keyword_details_content"><%= I18n.t('keywords.keyword') %>: <%= keyword.content %></p>
  <p data-testid="keyword_details_links_count"><%= I18n.t('keywords.links_count') %>: <%= keyword.links_count %></p>
  <p data-testid="keyword_details_top_ads_count"><%= I18n.t('keywords.total_ads_count') %>: <%= search_entries_query.top_ads_count %></p>
  <p data-testid="keyword_details_total_ads_count"><%= I18n.t('keywords.total_ads_count') %>: <%= search_entries_query.total_ads_count %></p>
  <p data-testid="keyword_details_non_ads_count"><%= I18n.t('keywords.non_ads_count') %>: <%= search_entries_query.non_ads_count %></p>

  <div data-testid="keyword_details_top_ads_urls">
    <%= render('url_list', urls: search_entries_query.top_ads_urls, title:  I18n.t('keywords.top_ads_urls')) %>
  </div>

  <div data-testid="keyword_details_non_ads_urls">
    <%= render('url_list', urls: search_entries_query.non_ads_urls, title: I18n.t('keywords.non_ads_urls')) %>
  </div>

  <div data-testid="keyword_details_page_view">
    <p><%= I18n.t('keywords.page_view') %>:</p>
    <iframe srcdoc="<%= keyword.result_page_html %>" class="keyword-details__page-view"></iframe>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='<%= I18n.locale %>' class="layout-default">
  <head>
    <title>GoogleScraperRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="<%= "#{controller_name.dasherize} #{action_name.dasherize}" %> px-4 py-2">
    <% if current_user %>
      <%= render "shared/app_header" %>
    <% end %>

    <%= render "shared/alert" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_alert.erb
<div class="container mt-2">
  <div>
    <% if flash[:alert] %>
      <div class="alert alert-danger" data-testid="alert-error">
        <% flash_alerts.each do |error| %>
          <p class="mb-0"><%= error %></p>
        <% end %>
      </div>
    <% end %>

    <% if flash[:notice] %>
      <p class="alert alert-success" data-testid="alert-notice"><%= flash[:notice] %></p>
    <% end %>
  </div>
</div>

app/views/shared/_app_header.erb
<header class="app-header">
  <%= button_to(
    I18n.t('auth.sign_out'),
    destroy_user_session_path,
    method: :delete,
    class: "app-header__sign-out btn btn-secondary"
  ) %>
</header>